export interface GitResponse {
  status:  number;
  url:     string;
  headers: { [key: string]: string };
  // headers: Header
  data:DataCommits[];
}

export interface DataCommits {
  sha:          string;
  node_id:      string;
  commit:       Commit;
  url:          string;
  html_url:     string;
  comments_url: string;
  author:       Author;
  committer:    Author;
  parents:      Parent[];
}

export interface Author {
  login:               string;
  id:                  number;
  node_id:             string;
  avatar_url:          string;
  gravatar_id:         string;
  url:                 string;
  html_url:            string;
  followers_url:       string;
  following_url:       string;
  gists_url:           string;
  starred_url:         string;
  subscriptions_url:   string;
  organizations_url:   string;
  repos_url:           string;
  events_url:          string;
  received_events_url: string;
  type:                string;
  site_admin:          boolean;
}
export interface Commit {
  author:        CommitAuthor;
  committer:     CommitAuthor;
  message:       string;
  tree:          Tree;
  url:           string;
  comment_count: number;
  verification:  Verification;
}

export interface CommitAuthor {
  name:  string;
  email: string;
  date:  string;
}

export interface Tree {
  sha: string;
  url: string;
}

export interface Verification {
  verified:  boolean;
  reason:    string;
  signature: null;
  payload:   null;
}

export interface Parent {
  sha:      string;
  url:      string;
  html_url: string;
}


// Generated by https://quicktype.io
// Generated by https://quicktype.io
export interface Header{
  "access-control-allow-origin": string
  "access-control-expose-headers": string,
  "cache-control": string,
  "content-encoding": string
  "content-security-policy": string
  "content-type": string
  date: string
  etag: string
  "github-authentication-token-expiration": string
  "last-modified": string
  "referrer-policy":string
  server: string
  "strict-transport-security": string
  "transfer-encoding": string
  vary: string
  "x-accepted-oauth-scopes": string
  "x-content-type-options": string
  "x-frame-options": string,
  "x-github-api-version-selected": string
  "x-github-media-type": string
  "x-github-request-id": string
  "x-oauth-scopes": string
  "x-ratelimit-limit": string
  "x-ratelimit-remaining": string
  "x-ratelimit-reset": string
  "x-ratelimit-resource": string
  "x-ratelimit-used": string
  "x-xss-protection": string
}

export interface frontendResponse {
  name: string
  avatar: string
  mail: string
  commit: string
  url: string
  created: string 
}